ProjectRoot/books/urls.py
from django.urls import path
from . import views
'''
클래스형 뷰를 사용하기 위한 URLConf 설정.
각 항목마다 as_view() 함수를 사용한다.

path() 함수 : route, view 2개의 필수인자와 kwargs, name 2개의 선택인수를 받는다.
    route : URL패턴을 표현하는 문자열로 URL스트링이라고 한다.
    view : URL스트링이 매칭되면 호출되는 View함수. 
        HttpRequest 객체와 URL스트링에서 추출된 항목이 View 함수의 인자로 전달된다.
    kwargs : URL스트링에서 추출된 항목 외에 추가적인 인자를 View함수로 전달할때
        파이썬의 딕셔너리 타입으로 인자를 정의한다.
    name : 각 URL패턴별로 별칭을 붙여준다. 여기서 정한 이름은 주로 템플릿에서 사용하게 된다.
'''
app_name = 'books'
urlpatterns = [
    path('',views.BooksModelView.as_view(), name='index'),
    path('book/',views.BookList.as_view(), name='book_list'),
    path('author/',views.AuthorList.as_view(), name='author_list'),
    path('publisher/',views.PublisherList.as_view(), name='publisher_list'),
    path('book/<int:pk>/',views.BookDetail.as_view(), name='book_detail'),
    path('author/<int:pk>/',views.AuthorDetail.as_view(), name='author_detail'),
    path('publisher/<int:pk>',views.PublisherDetail.as_view(), name='publisher_detail'),
]
'''
/books/book/ ⇒ 목록
/books/author/ ⇒ 목록
/books/publisher/ ⇒ 목록
/books/book/일련번호/ ⇒ 상세보기 
/books/author/일련번호/ ⇒ 상세보기
/books/publisher/일련번호/ ⇒ 상세보기 
'''

ProjectRoot/books/models.py
from django.db import models

# 책 테이블 생성
class Book(models.Model):
    # 제목
    title = models.CharField(max_length=100)
    # 저자이름 : Author 테이블의 PK와 N:N의 관계를 설정. 저자는 여러권의 책을 쓸수 있다.
    authors = models.ManyToManyField('Author')
    # 출판사 : Publisher 테이블의 PK와 1:N의 관계를 설정. 책은 한 출판사에서만 출간된다.
    # on_delete=models.CASCADE 옵션은 오라클과 동일하게 부모레코드가 삭제될때 자식까지 같이 삭제된다.
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    # 출판일
    # publication_date = models.DateTimeField('date published') #일종의 설명문
    publication_date = models.DateField()

    def __str__(self):
        return self.title

# 저자 테이틀 생성
class Author(models.Model):
    name = models.CharField(max_length=50) # 저자이름
    salutation = models.CharField(max_length=100) # 인사말
    email = models.EmailField() # 이메일
    
    def __str__(self):
        return self.name

# 출판사 테이블 생성
class Publisher(models.Model):
    name = models.CharField(max_length=50) # 출판사명
    address = models.CharField(max_length=100) # 주소
    website = models.URLField() # 웹사이트URL
    
    def __str__(self):
        return self.name
    

ProjectRoot/books/views.py
import django
from django.shortcuts import render
# 클래스형 제네릭뷰를 사용하기 위한 임포트
from django.views.generic.base import TemplateView  # 테블릿뷰
from django.views.generic import ListView           # 리스트뷰
from django.views.generic import DetailView         # 디테일뷰
# 레코드 조회를 위한 모델 클래스 임포트
from books.models import Book, Author, Publisher

# books 애플리케이션 첫 화면을 출력
class BooksModelView(TemplateView): # 해당클래스는 TemplateView를 상속하여 정의
    # TemplateView를 사용하는 경우 해당 클래스 변수를 오버라이딩 해야한다.
    template_name = 'books/index.html' # 템플릿 파일 경로를 지정한다.
    # 함수형 뷰 처럼 render()함수를 통해 반환하지 않아도 자동으로 호출된다.
    
    # 템플릿으로 전달할 데이터가 있는 경우 get_context_data()를 오버라이딩 한다.
    def get_context_data(self, **kwargs): # 자동완성 지원됨
        # 오버라이딩 하는 경우 반드시 super()를 첫줄에 선언해야 한다.
        context = super().get_context_data(**kwargs)
        # 템플릿으로 전달할 데이터 저장
        context["model_list"] = ['Book', 'Author', 'Publisher']
        # return도 필수적으로 필요하다.
        return context

'''
제네릭뷰 중 ListView를 사용하여 리스트 구현
    : ListView를 상속받는 경우 해당 코델 클래스를 템플릿으로 전달하는 것 만으로
      리스트 구성, 컨텍스트 변수 저장 및 전달이 자동으로 처리된다.
      또한, 디폴트로 지정되는 2가지가 있는데
        첫째 : 컨텍스트 변수로 object_list를 사용한다.
        둘째 : 템플릿 파일명은 "모델명소문자_list.html'로 지정된다.
'''
class BookList(ListView):
    # 1. Book 테이블로부터 모든 레코드를 가져와서 컨텍스트 변수 object_list에 저장한다.
    # 2. 템플릿 파일은 "books/book_list.html"과 같이 지정되어 컨텍스트 변수가 전달된다.
    # 3. 이 부분이 자동으로 처리된다.
    model = Book
class AuthorList(ListView):
    model = Author
class PublisherList(ListView):
    model = Publisher
'''
제네릭뷰 중 DetailView를 사용하여 상세페이지 구현
    : DetailView를 상속하는 경우 특정 레코드 하나를 조회한 후 컨텍스트 변수에 저장한다.
      URLConf에서 지정한 파라미터를 통해 특정 레코드 하나를 조회한 후 템플릿으로 전달하게 한다.
'''
class BookDetail(DetailView):
    # 1. 테이블로부터 조회한 값은 object라는 변수명으로 컨텍스트에 저장한다.
    # 2. "모델명소문자_detail.html"이라는 템플릿 파일명을 찾아 렌더링 한다.
    model = Book
class AuthorDetail(DetailView):
    model = Author
class PublisherDetail(DetailView):
    model = Publisher

ProjectRoot/books/templates/base_books.html
<!-- 템플릿 상속됨 -->
{% extends 'basic.html' %}

<title>{% block title %}Books Application Site{% endblock %}</title>

{% block sidebar %}

<!-- 부모 템플릿인 basic.html 에서 정의한 것을 하위에서 재사용한다. -->
{{ block.super }}
<ol>
    <li><a href="/books/">Books Home</a></li>
</ol>

{% endblock %}

ProjectRoot/books/templates/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{% block title %}Books기본템플릿{% endblock %}</title>
</head>
<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Project Home</a></li>
            <li><a href="/admin/">Admin페이지</a></li>
        </ul>
        {% endblock %}
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

ProjectRoot/books/templates/books/author_detail.html
{% extends 'base_books.html' %}

{% block content %}
    <h2>{{ object.name }}</h2>
    <p>{{ object.salutation }}</p>
    <li>Email : {{ object.email }}</li>
{% endblock content %}

ProjectRoot/books/templates/books/author_list.html
{% extends 'base_books.html' %}

{% block content %}
    <h2>Author List</h2>
    <ul>
    {% for author in object_list %}
        <li>
            <a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a>
        </li>
    {% endfor %}
    </ul>
{% endblock content %}

ProjectRoot/books/templates/books/book_detail.html
{% extends 'base_books.html' %}

{% block content %}
    <h2>{{ object.title }}</h2>
    <ul>
        <li>
            Authors : 
            <!-- 저자의 경우 공저의 개념이 있어 하나의 책을 두명이상의 저자가 공동집필하는 경우가 있다.
                따라서, 아래는 object에 연결된 authors 모두를 가져와서 출력하겠다는 의미이다. -->
            {% for author in object.authors.all %}
                {{ author }}
                <!-- 저자를 출력할때 마지막이 아닌 경우에만 콤마를 출력한다.
                    즉, 마지막에는 콤마를 출력하지 않는다. -->
                {% if not forloop.last %}, {% else %}{% endif %}
            {% endfor %}
        </li>
        <li>Publisher : {{ object.publisher }}</li>
        <li>Publication date : {{ object.publication_date }}</li>
    </ul>
{% endblock content %}

ProjectRoot/books/templates/books/book_list.html
{% extends 'base_books.html' %}

{% block content %}
    <h2>Book List</h2>
    <ul>
    <!-- View에 전달해준 context변수가 object_list임으로 이를 통해 반복 출력 -->
    {% for book in object_list %}
        <li>
            <!-- 
                url 태그를 통해 'books:book_detail'로 지정된 URL패턴을 찾아 URL을 생성한다.
                즉, path('book/<int:pk>/',views.BookDetail.as_view(), name='book_detail'),
                위 부분를 찾게 된다.
                book.id는 Book테이블의 일련번호(PK)로 지정되어 있는 컬럼이다.
             -->
            <a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a>
        </li>
    {% endfor %}
    </ul>
{% endblock content %}

ProjectRoot/books/templates/books/index.html
<!-- base_books.html 템플릿 파일을 상속 -->
{% extends 'base_books.html' %}

<!-- block태그를 통해 content 생성 -->
{% block content %}
    <h2>Books Management System</h2>
    <ul>
    <!-- 
        Views.py에서 생성한 context["model_list"] = ['Book', 'Author', 'Publisher']
        를 대상으로 반복 출력한다.
     -->
    {% for modelname in model_list %}
        <!-- 
            add(문자열연결), lower(소문자) 템플릿 필터를 사용해서 문자열을 생성한다.
            Book => book_list
            즉, URLConf에서 "books:book_list"라는 별칭을 찾아 URL을 생성한다.
        -->
        {% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
        <!-- with 블럭내에서만 사용할 수 있는 변수를 생성한다.
            만들어서 urlvar이라는 변수에 저장한다.
        -->
        <li>
            <!-- href="/books/book/" 와 같은 형태의 링크가 생성된다. -->
            <a href="{% url urlvar %}">{{ modelname }}</a>
        </li>
        {% endwith %}
    {% endfor %}
    </ul>
{% endblock %}

ProjectRoot/books/templates/books/publisher_detail.html
{% extends 'base_books.html' %}

{% block content %}
    <h2>{{ object.name }}</h2>
    <p>{{ object.website }}</p>
    <li>Address : {{ object.address }}</li>
{% endblock content %}

ProjectRoot/books/templates/books/publisher_list.html
{% extends 'base_books.html' %}

{% block content %}
    <h2>Publisher List</h2>
    <ul>
    {% for publisher in object_list %}
        <li>
            <a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a>
        </li>
    {% endfor %}
    </ul>
{% endblock content %}