ProjectRoot/livepolls/urls.py
from django.urls import path
from . import views

# app_name은 차후 URL처리를 위한 네임스페이스로 활용된다.
app_name = 'livepolls'

# 네임스페이스로 처리됨으로 livepolls/를 제외한 URL패턴을 기술하면 된다. 
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:question_id>/', views.detail, name='detail'), # /livepolls/일련번호
    path('<int:question_id>/results/', views.results, name='results'), # /livepolls/일련번호/results/
    path('<int:question_id>/vote/', views.vote, name='vote'), # /livepolls/일련번호/vote/
]

ProjectRoot/livepolls/models.py
from django.db import models

'''
장고에서는 테이블을 하나의 클래스로 정의하고,
테이블의 컬럼은 클래스의 변수로 매핑한다.
django.db.models.Model 클래스를 상속받아 정의하고,
각 클래스 변수의 타입도 장고에서 미리 정의해둔 필드 클래스를 사용한다.
'''

# Question 테이블 생성 : 설문에 대한 질문
class Question(models.Model):
    '''
    PK(기본키)는 별도로 지정하지 않아도 장고에서 자동으로 생성해준다.
    컬럼명은 id로 not null, AutoIncrement 제약조건이 추가된다.
    '''
    question_text = models.CharField(max_length=200) # varchar(200)
    pub_date = models.DateTimeField('date published') # datetime , 문자열은 일종의 설명문

    '''
    객체를 문자열로 표현할때 사용한다. 해당 함수를 정의하지 않으면
    테이블명이 제대로 표시되지 않는다.
    '''
    def __str__(self):
        return self.question_text
    
#Choice 테이블 생성 : 질문에 대한 답변 항목
class Choice(models.Model):
    '''
    FK는 항상 부모 테이블의 PK와 연결됨으로 Question클래스만 지정하면 된다.
    FK로 지정된 컬럼은 자동으로 _id라는 접미사가 붙게 된다.
    '''
    question = models.ForeignKey(Question, on_delete=models.CASCADE) # 외래키 설정
    choice_text = models.CharField(max_length=200) # varchar(200), 답변항목
    votes = models.IntegerField(default=0) # Integer, 투표수
    
    def __str__(self):
        return self.choice_text

ProjectRoot/livepolls/views.py
'''
단축함수 : 장고에서 웹 프로그램 개발시 자주 사용하는 기능들을
    내장함수로 제공하고 있는데 이를 단축함수라 표현한다.
    render() 함수 등이 있다. 
'''
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
# Model을 사용하기 위한 import
from livepolls.models import Choice, Question

from django.shortcuts import get_object_or_404

# 메인화면 : 기능은 없고 단순히 바로가기 링크만 있음.
def main(request): # views에 함수 정의시 request 내장객체는 필수요소임
    return render(request, 'livepolls/main.html')

# 투표앱의 첫번째 화면으로 질문이 리스팅된다.
def index(request):
    # Question 테이블에서 pub_date를 내림차순으로 정렬하여 최근 게시물 5개를 가져온다.
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    # 템플릿으로 데이터를 전달하기 위해 딕셔너리로 저장한다.
    context = {'latest_question_list' : latest_question_list}
    # render함수를 통해 템플릿을 로드하면서 데이터를 전달한다.
    return render(request, 'livepolls/index.html', context)

'''
get_object_or_404(모델클래스, 검색조건)
    : 모델클래스(테이블)에서 검색 조건에 맞는 객체를 조회하여 반환한다.
      만약 조건에 맞는 객체가 없다면 Http404를 발생시킨다.
'''
def detail(request, question_id):
    # URL 패턴을 통해 전달된 일련번호로 Question테이블을 검색 후 반환한다.
    question = get_object_or_404(Question, pk=question_id)
    # 조회된 데이터를 딕셔너리를 통해 템플릿으로 반환한다.
    return render(request, 'livepolls/detail.html',{'question': question})

# 투표 처리 : 선택한 항목의 vote 컬럼을 +1한다
def vote(request, question_id):
    # 선택한 질문의 일련번호를 통해 레코드를 가져온다.
    question = get_object_or_404(Question, pk=question_id)
    try:
        # detail페이지에서 선택한 항목을 통해 choice테이블에서 레코드를 가져온다.
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # 예외발생 되면 detail페이지를 다시 보여준다. 이때 에러메세지를 전달한다.
        return render(request, 'livepolls/detail.html', {
            'question':question,
            'error_message' : "You didn't select a choice",
        })
    else:
        # try 절의 코드가 정상실행되면 가져온 레코드를 통해 votes항목을 +1 업데이트한다.
        selected_choice.votes += 1
        # 앞에서 처리한 내용을 실제 테이블에 적용한다.
        selected_choice.save()
        # 정상 처리되면 result 페이지로 이동한다.
        return HttpResponseRedirect(reverse('livepolls:results', args=(question.id,)))
        '''
            reverse(urls의 별칭, 인수)
                : 별칭과 인수를 통해 URL을 만들기 위한 함수이다.
                  - 보통방식 : 요청이 있을때 URL을 분석한 후 필요한 views를 호출.
                  - reverse방식 : 별칭을 통해 거꾸로 URL을 만든다.
        '''

# 투표 결과 보기
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'livepolls/results.html', {'question': question})

ProjectRoot/livepolls/templates/livepolls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>투표Detail</title>
</head>
<body>
    <!-- 투표의 질문을 문서의 제목으로 사용 -->
    <h1>{{ question.question_text }}</h1>

    <!-- 
        에러가 있는 경우 메세지를 보여준다.
        vote() 뷰 함수의 try~except 부분에서 예외가 발생하면
        error_message를 추가하여 렌더링 할 것이다.
    -->
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'livepolls:vote' question.id %}" method="post">
    <!-- 폼을 처리하는 경우 CSRF(Cross Site Request Forgery) 공격 방어 -->
    {% csrf_token %}
    <!-- View함수에서 넘겨준 객체를 통해 갯수만큼 반복하여 라디오버튼을 출력한다. -->
    <!-- 
        choice_set : Question과 Choice 테이블의 관계는 1:N의 관계이고,
            외래키로 연결되어 있을때 자식테이블의 항목을 의미한다.
     -->
    {% for choice in question.choice_set.all %}
        <!-- forloop.counter : 실제 반복횟수를 반환해주는 객체로 템플릿 문법에서 좀 더 자세히 다루도록 한다. -->
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
        <!-- input의 id속성과 label의 for속성값을 일치시켜 클릭의 범위를 확대한다. -->
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    {% endfor %}
    <input type="submit" value="Vote">
    </form>
</body>
</html>

ProjectRoot/livepolls/templates/livepolls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>투표index</title>
</head>
<body>
    <h2>라이브 투표 하기</h2>
    <!-- latest_question_list에 데이터가 있다면 갯수만큼 반복한다 -->
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <!-- 
                id : 일련번호 컬럼(PK)
                question_text : 투표의 질문 항목
             -->
            <li><a href="/livepolls/{{ question.id }}/">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>등록된 항목이 없습니다.</p>
    {% endif %}
</body>
</html>

ProjectRoot/livepolls/templates/livepolls/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>장고 애플리케이션 메인</title>
</head>
<body>
    <h2>여기는 Main</h2>
    <ul>
        <li><a href="./livepolls/" target="_blank">투표 애플리케이션 바로가기</a></li>
        <li><a href="./tempapps/" target="_blank">템플릿 Apps 바로가기</a></li>
        <li><a href="./books/" target="_blank">도서관리 애플리케이션 바로가기</a></li>
    </ul>
</body>
</html>

ProjectRoot/livepolls/templates/livepolls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>투표Results</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
    <!-- Question테이블과 외래키 관계가 있는 자식 테이블의 레코드를 가져와서 출력한다. -->
    {% for choice in question.choice_set.all %}
        <!-- 선택항목 -- 투표수(복수형 접미사에 의해 s가 붙을지 결정한다.) -->
        <li>{{ choice.choice_text }} -- {{ choice.votes }}
            vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>
    <a href="{% url 'livepolls:detail' question.id %}">재투표 하시겠습니까?</a>
    &nbsp;
    <a href="/">Main 바로가기</a>
</body>
</html>