ProjectRoot/tempapps/urls.py
from django.urls import path
from . import views

app_name = 'tempapps'
urlpatterns = [
    path('', views.index, name='index'),
    path('template.filter/', views.templateFilter, name="my_filter"), # 템플릿 필터
    path('template.tag/', views.templateTag, name="my_tag"), # 템플릿 태그
    path('form.create/', views.formCreate, name="formCreate"), # 폼 사용하기
    path('boardWrite/', views.boardWrite, name="boardWrite"), # 글쓰기 페이지
    path('thanks/', views.thanks),
]

ProjectRoot/tempapps/models.py
from django.db import models

# Create your models here.

ProjectRoot/tempapps/forms.py
from django import forms
from django.forms import widgets
from django.http import request
'''
장고에서 제공하는 Form기능을 사용하려문 우선 forms.Form 클래스를 상속한다.
각 변수명은 해당 input태그의 name속성값으로 사용된다.
태그 생성시 required 속성이 포함되어 기본적인 빈값 검증을 하게 된다.
'''
class QuestionForm(forms.Form):
    # <input type="text"를 생성.label은 타이틀로 사용.
    user_id = forms.CharField(label='아이디', max_length=10)
    # 가장 기본적인 input태그를 생성. 타이틀은 변수명과 동일하게 (title)로 표시된다.
    title = forms.CharField()
    # 여러줄의 텍스트를 입력할 수 있는 <textarea>를 생성.
    content = forms.CharField(widget=forms.Textarea)
    # 기본적인 input 태그를 성상하되 type='email'로 생성.
    email = forms.EmailField()
    # <input type="checkbox" 를 생성. 
    my_check = forms.BooleanField(required=False)
    # required=False => 유효성 검증을 하지 않는다.

    ############################################################################################
    data01 = ['유비','관우','장비']
    data02 = [
        ('red','빨강'),('green','녹색'),('blue','파랑'),('black','검정')
    ]
    
    #<input type="text" name="form1" required id="id_form1">
    form1 = forms.CharField(widget=forms.TextInput)
    #<input type="number" name="form2" required id="id_form2">
    form2 = forms.CharField(widget=forms.NumberInput)
    #<input type="password" name="form3" required id="id_form3">
    '''
    추가적인 속성을 부여할때는 위젯에 attrs을 기술한다.
    '''
    form3 = forms.CharField(
        widget=forms.PasswordInput(attrs={'size':30})
    )
    #<textarea name="form4" cols="40" rows="10" required id="id_form4">
    form4 = forms.CharField(widget=forms.Textarea)
    '''
    select태그를 표현한다. (1개 선택)
    choices : select태그의 option태그를 구성하는 데이터로 사용한다.
        순서대로 value와 text로 사용된다.
    initial : 해당 태그의 default값으로 사용된다.
        주로 수정에서 활용하면 된다.
        
    <select name="form5" id="id_form5">
        <option value="red">빨강</option>
        ....
        <option value="blue" selected>파랑</option>
    </select>
    '''
    form5 = forms.ChoiceField(
        widget=forms.Select,
        choices=data02,
        initial='blue'   # 디폴트값(없을시 첫번째목록)
    )
    '''
    select태그를 표현하는 것은 5번과 동일하지만 multiple 속성을 부여하여
    2개 이상의 항목을 선택할 수 있게 한다.
    또한 default값을 표현하기 위해 2개 이상의 항목을 선택할 수 있어야 함으로
    리스트를 사용해야 한다.
    (멀티 선택)
    '''
    form6 = forms.MultipleChoiceField(
        widget=forms.SelectMultiple,
        choices=data02,
        initial=['black','green']
    )
    '''
    <div id="id_form7">
        <div>
            <label for="id_form7_0">
                <input type="radio" name="form7" value="red" required id="id_form7_0">빨강
            </label>
        </div>
        <div>
            <label for="id_form7_1">
                <input type="radio" name="form7" value="green" required id="id_form7_1">녹색
            </label>
        </div>
    </div>
    라디오 버튼을 표현한다.(1개 선택)
    '''
    form7 = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=data02,
        initial = 'blue'
    )
    '''
    체크박스를 표현한다.(멀티 선택)
    추가적인 속성을 부여할때는 attrs={'class':'red'} 와 같이 기술한다.
    '''
    form8 = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={'class':'red'}),
        choices=data02,
        initial=['black', 'green'],
    )
    
    # 파일 <input type="file" name="form9" required="" id="id_form9">
    form9 = forms.CharField(
        widget=forms.FileInput(attrs={'class': 'blue'}), 
        label="첨부파일", 
    )

# 게시판의 글쓰기 페이지 UI 구현
class WriteForm(forms.Form):
    '''
        attrs 속성으로 각 폼에 class를 부여한다.
        가로 사이즈 조정을 위해 w100 클래스가 추가되었다.
        첨부파일의 경우 필수사항이 아니므로 required=False 추가한다.
        입력폼의 타이틀 부분을 한글로 처리하기 위해 label을 추가한다.
    '''
    my_name = forms.CharField(
        label = '작성자',
        widget = forms.TextInput(attrs={'class':'form-control w100'})
    )
    my_pass = forms.CharField(
        label = '패스워드',
        widget = forms.TextInput(attrs={'class':'form-control w200'})
    )
    my_title = forms.CharField(
        label = '제목',
        widget = forms.TextInput(attrs={'class':'form-control'})
    )
    my_content = forms.CharField(
        label = '내용',
        widget = forms.Textarea(attrs={'class':'form-control'})
    )
    my_file = forms.FileField(
        label = '첨부파일',
        widget = forms.FileInput(attrs={'class':'form-control'}),
        required=False
    )
    

ProjectRoot/tempapps/views.py
from django.shortcuts import render
from tempapps.forms import WriteForm
from tempapps.boardWriteForm import boardWriteForm
from tempapps.forms import QuestionForm
from django.http import HttpResponseRedirect

# tempapps의 index 화면 : 바로가기 링크만 있음
def index(request):
    return render(request, 'index.html')

# Template Filter를 사용하기 위한 여러 종류의 변수 선언 및 Template 호출
def templateFilter(request):
    # 정수형 변수
    num1 = 1
    num2 = 10
    # 문자형 변수
    engStr = "nakja's MustHave\r\njava <b>web</b>programming" # 특수기호+HTML태그
    hanStr = "낙자쌤의 자바 웹 프로그래밍"
    # 컬렉션형 변수
    dictVar = {'a':'유비', 'b':'관우', 'c':'장비'} # 딕셔너리
    listVar = ['손오공','저팔계','사오정']         # 리스트

    context={'num1':num1, 'num2':num2, 'engStr':engStr, 'hanStr':hanStr, 'dictVar':dictVar, 'listVar':listVar}
    # 템플릿 호출 및 값 전달
    return render(request, 'template_filter.html', context)
    
# 템플릿 태그
def templateTag(request):
    # 딕셔너리를 인자로 가진 리스트
    books = [
        {'name':'자바', 'price':1000},
        {'name':'HTML', 'price':2000},
        {'name':'JSP', 'price':3000},
    ]
    # 빈 리스트
    hobbys = []
    favorites = ['운동','공부','여행','경제']
    iVar = range(1,11)

    context = {'books':books, 'hobbys':hobbys, 'favorites':favorites, 'iVar':iVar }
    return render(request, 'template_tag.html', context)

# 장고의 폼 생성기능 사용하기
def formCreate(request):
    '''
    Servlet의 doGet(), doPost()와 같이 하나의 함수에서
    폼 출력과 전송된 값 처리를 동시에 하도록 권장하고 있다.
    즉, POST인 경우라면 폼값을 입력한 후 전송할때의 처리를 말한다.
    '''
    if request.method == 'POST':
        # 진입 시 전송방식이 POST라면 submit된 폼값을 처리한다.
        form = QuestionForm(request.POST)
        # 폼값의 유효성 빈값 검증을 한다.
        if form.is_valid():
            # 폼 데이터가 유효하면 클린데이터로 복사한다.
            user_id = form.cleaned_data['user_id']
            # user_id외에 title, content도 동일한 방식으로 저장할 수 있다.
            
            # 폼 데이터에 문제가 없다면 DB에 입력하거나 혹은 비즈니스로직을 수행한다.
            
            # return HttpResponseRedirect('/thanks/') # 페이지 이동
            return render(request, 'thanks.html', {'user_id':user_id}) # 템플릿 렌더링
    else:
        # 전송방식이 GET이라면 입력폼으로 진입한다.
        form = QuestionForm()
    # 입력폼 진입을 위해 템플릿을 렌더링한다.
    return render(request, 'form_create.html', {'form':form})
    

def thanks(request):
    return render(request, 'thanks.html')
'''
def boardWrite(request):
    if request.method == 'POST':
        form = boardWriteForm(request.POST)
        if form.is_valid():
            user_name = form.cleaned_data['user_name']
            return render(request, 'boardWriteThx.html', {'user_name':user_name})    
    else:
        form = boardWriteForm()
    return render(request, 'boardWrite.html', {'form':form})
'''
def boardWrite(request):
    #template_path = ''
    if request.method == 'POST':
        template_path = 'boardWrite.html'
    else:
        form = WriteForm()
        template_path = 'boardWrite.html'
    return render(request, template_path, {'form':form})

ProjectRoot/tempapps/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base.html파일</title>
    <link rel="stylesheet" href="{% static 'style2.css' %}" type="text/css">
</head>
<body>
    경로 : ProjectRoot\livepolls\template\base.html<br>

    {% block navbar %}
    {% endblock %}

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

ProjectRoot/tempapps/templates/boardWrite.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
	<style>
    	div{border:0px solid blueviolet;}
    	*{font-size: 12px;}
		.w100{width:100px;}
		.w200{width:200px;}
		/*
		웹브라우저의 개발자모드에서 인스펙트를 통해 복사한 셀렉터를 통해 스타일을 부여한다.
		table의 모든 th태그에 수평/수직 방향으로 가운데 정렬한다.
		*/
		#writeTable > tbody > tr > th{
			text-align: center;
			vertical-align: middle;
		}
	</style>
</head>
<body>
<div class="container">
	<!-- Top영역 -->
    
    <div class="row">
    	<div class="col-12">
        	<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            	<div class="container-fluid">
                	<!-- 회사로고(logo) -->
                	<a class="navbar-brand" href="#">
                    	<img src="https://www.ikosmo.co.kr/images/common/logo_center_v2.jpg" style="width: 120px;">
                	</a>
                	<!-- GNB(Global Navigation Bar : 해당 웹사이트의 전체(global) 메뉴) -->
                	<ul class="navbar-nav">
                    	<li class="nav-item">
                        	<a class="nav-link active" href="#">자유게시판</a>
                    	</li>
                    	<li class="nav-item">
                        	<a class="nav-link" href="#">자료실</a>
                    	</li>
                    	<li class="nav-item dropdown">
                        	<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">드롭다운</a>
                        	<ul class="dropdown-menu">
                            	<li><a class="dropdown-item" href="#">Link 1</a></li>
                            	<li><a class="dropdown-item" href="#">Link 2</a></li>
                            	<li><a class="dropdown-item" href="#">Link 3</a></li>
                        	</ul>
                    	</li>
                	</ul>
                	<!-- 검색폼 -->
                	<form class="mt-3" method="get" action="">
                	<div class="input-group mb-3">
                    	<input type="text" class="form-control" placeholder="Search" style="width: 200px;">
                    	<button class="btn btn-warning" type="submit">
                        	<i class="bi-search" style="font-size: 1rem; color: white;"></i>
                    	</button>
                	</div>
                	</form>
                	<!-- 회원가입/로그인 링크 -->
                	<ul class="navbar-nav">
                    	<!-- 로그인전 -->
                    	<li class="nav-item">
                        	<a class="nav-link" href="#">
                            	<i class="bi-person-plus-fill" style="font-size: 1rem;"></i>
                            	회원가입
                        	</a>
                    	</li>
                    	<li class="nav-item">
                        	<a class="nav-link" href="#">
                            	<i class="bi-box-arrow-in-right" style="font-size: 1rem;"></i>
                            	로그인
                        	</a>
                    	</li>
                    	<!-- 로그인후 -->
                    	<!-- <li class="nav-item">
                        	<a class="nav-link" href="#">
                            	<i class="bi-person-lines-fill" style="font-size: 1rem;"></i>
                            	회원정보수정
                        	</a>
                    	</li>
                    	<li class="nav-item">
                        	<a class="nav-link" href="#">
                            	<i class="bi-box-arrow-right" style="font-size: 1rem;"></i>
                            	로그아웃
                        	</a>
                    	</li> -->
                	</ul>
            	</div>
        	</nav>
    	</div>
	</div>
	<!-- Body영역 -->
	<div class="row">
    	<!-- Left메뉴영역 -->
   	 
<div class="col-3">
      	<div style="height: 100px;line-height: 100px;text-align: center;background-color: cadetblue;
    	border-radius: 10px;margin: 10px 0;font-size: 1.5em;color: #ffffff;">
    	웹사이트제작
	</div>
	<ul class="nav nav-pills flex-column">
    	<li class="nav-item">
        	<a class="nav-link active" href="#">자유게시판</a>
    	</li>
    	<li class="nav-item bg-light">
        	<a class="nav-link" href="#">자료실</a>
    	</li>
    	<li class="nav-item bg-light dropdown dropend">
        	<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">쇼핑하기</a>
        	<ul class="dropdown-menu">
            	<li><a class="dropdown-item" href="#">Link 1</a></li>
            	<li><a class="dropdown-item" href="#">Link 2</a></li>
            	<li><a class="dropdown-item" href="#">Link 3</a></li>
        	</ul>
    	</li>
	</ul>
</div>
    	<!-- Contents영역 -->
    	<div class="col-9 pt-3">
        	<h3>게시판 작성 - <small>자유게시판</small></h3>
       	 
        	<form method="post">
                {% csrf_token %}
            	<table class="table table-bordered" id="writeTable">
					<colgroup>
						<col width="20%"/>
						<col width="*"/>
					</colgroup>
                <!-- Django를 통한 Form 만들기 -->
				
				<!-- 
                {% block boardWrite %}
					{{ form.as_table }}
                {% endblock %}
 				-->

				<tbody>

					{{ form.as_table }}

				</tbody>
            	</table>

            	<!-- 각종버튼 -->
            	<div class="row mb-3">
                	<div class="col d-flex justify-content-end">
                    	<button type="submit" class="btn btn-primary">글쓰기</button>
                    	<button type="reset" class="btn btn-dark">다시쓰기</button>
                	</div>
            	</div>
        	</form>
    	</div>
	</div>
	<!-- Copyright영역 -->
    
<div class="row border border-dark border-bottom-0 border-start-0 border-end-0 pt-2">
	<div class="col-2">
      	<h2>낙짜쌤&trade;</h2>
	</div>
	<div class="col-10">
      	Email : 본인의&nbsp;&nbsp;
      	Mobile : 정보를&nbsp;&nbsp;
      	Address : 쓰세요
      	<br>
      	copyright &copy; 2021
      	All right reserved.
	</div>
</div>
</div>
</body>
</html>

ProjectRoot/tempapps/templates/boardWriteThx.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>작성완료</title>
</head>
<body>
    <h2 style="display: inline-block;">{{ user_name }}</h2><span style="font-size: 14px;">&nbsp;님의 작성하신 글이 등록되었습니다.</span>
    <h3>감사합니다.</h3>
</body>
</html>

ProjectRoot/tempapps/templates/form_create.html
<!-- 
    해당 템플릿에서는 base.html 템플릿을 상속한다.
    템플릿 상속은 include와 비슷한 개념으로 기본 문서폼을 만든 후
    필요한 컨텐츠를 삽입하는 형식이다.
 -->
{% extends 'base.html' %}

<!-- 
    block태그를 이용해서 navbar를 생성한다.
    즉, navbar라는 변수에 블럭내의 html태그를 저장한다고 보면 된다.
-->
{% block navbar %}
    <ul>
        <li>네비메뉴1</li>
        <li>네비메뉴2</li>
        <li>네비메뉴3</li>
    </ul>
{% endblock %}

<!-- 
    장고의 form생성 기능을 사용하면 input태그를 포함한 <tr>,<li>,<p>로 감싼 컨텐츠를 반환한다.
    <form>, <table> 등은 개발자가 직접 기술해야 한다.
    as_table : <tr> 태그로 감싸서 반환
    as_p     : <p> 태그로 감싸서 반환
    as_ul    : <li> 태그로 감싸서 반환
 -->
{% block content %}
    <h2>Form 클래스 사용하기</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <table border="1">
            {{ form.as_table }}
        </table>
        <input type="submit" value="전송하기"> 
    </form>
{% endblock %}

ProjectRoot/tempapps/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>템플릿</title>
</head>
<body>
    <h1>템플릿 사용하기</h1>

    <ul>
        <li><a href="./template.filter/" target="_blank">템플릿 필터 바로가기</a></li>
        <li><a href="./template.tag/" target="_blank">템플릿 태그 바로가기</a></li>
        <li><a href="./form.create/" target="_blank">폼 사용하기</a></li>
        <li><a href="./boardWrite/" target="_blank">글쓰기 페이지</a></li>
    </ul>
</body>
</html>

ProjectRoot/tempapps/templates/template_filter.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style2.css' %}">
    <title>템플릿 필터 사용하기</title>
</head>
<body>
    <h3 class="red">템플릿 필터 사용하기</h3>

    <!-- 템플릿에서 변수를 출력할때에는 콧수염괄호(Mustache Tag)를 사용한다. -->
    <h4 class="blue">변수 출력</h4>
    숫자 : {{ num1 }}, {{ num2 }} <br>
    한글 : {{ hanStr }} <br>
    <!-- HTML태그는 기본적으로 사용할 수 없도록 특수기호로 변환된다. -->
    영어 : {{ engStr }}

    <!-- 컬렉션 변수를 출력할때는 반드시 닷(.)을 사용해야한다. -->
    <h4 class="green">변수에 도트(.) 사용</h4>
    딕셔너리 : {{ dictVar.a }}, {{ dictVar.b }} <br>
    리스트 : {{ listVar.0 }}, {{ listVar.2 }} <br>    
    {#{ listVar[1] } => 리스트를 이와같이 기술하면 에러가 발생됨 #}

    <h4>lower : 소문자로 변경</h4>
    {{ engStr|lower }}

    <!-- \r\n을 줄바꿈 처리해주고, 문장을 출력할때 <p>태그로 감싸준다. -->
    <h4>escape 및 linebreaks : 특수문자 이스케이프 및 줄바꿈</h4>
    {{ engStr|escape|linebreaks }}

    <!-- 인자로 주어진 3이 적용되어 세개의 단어까지만 잘라서 출력 -->
    <h4>truncatewords : 단어 단위로 자르기</h4>
    {{ hanStr|truncatewords:3 }} <br>
    {{ engStr|truncatewords:3 }}
    
    <!-- 인자로 주어진 4미만까지 적용되어 세개의 문자만 잘라서 출력 -->
    <h4>truncatechars : 문자 단위로 자르기</h4>
    {{ hanStr|truncatechars:4 }} <br>
    {{ engStr|truncatechars:4 }}

    <!-- 변수에 값이 없을때 디폴트값을 지정하여 출력한다. -->
    <h4>default : 디폴트값 지정</h4>
    {{ noStr|default:"값없음" }}
    
    <h4>length : 문자열의 길이</h4>
    {{ engStr|length}}
    
    <h4>striptags : HTML태그를 모두 제거</h4>
    {{ engStr|striptags}}


    <h4>복수형 접미사 : pluralize</h4>  
    1일때 : {{ num1|pluralize }} <br>           {# 단수임으로 아무것도 안나옴 #}
    10일때(기본) : {{ num2|pluralize }} <br>    {# 2이상(복수)일떄는 s가 출력 #}
    10일때(커스텀) : {{ num2|pluralize:"sss" }} {# sss 출력됨 #}

    <h4>add : 덧셈결과</h4>
    {{ num1|add:"2" }} <br>
    {{ num2|add:"2" }} <br>
    {{ engStr|add:"2" }} {# 문자열인 경우 숫자와 연결되어 출력 #}

    <!-- 장고 프레임워크는 기본적으로 HTML태그는 실행되지 않도록 처리된다.
    문자열 사이에 <script>와 같은 태그를 통해 해킹의 우려가 있음으로 원천적으로 차단하기 위함이다.
    HTML태그를 사용해야하는 특별한 경우에 아래와 같이 autoescape를 사용한다. -->
    <h4>HTML 태그 렌더링하기</h4>
    {% autoescape off %}
    {{ engStr }}
    {% endautoescape %}
</body>
</html>

ProjectRoot/tempapps/templates/template_tag.html
<!-- static 디렉토리를 사용하기 위한 준비 -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>템플릿 태그</title>
    <style>
        body{font-size: 20px;}
    </style>
    <!-- static 디렉토리에 저장된 css파일을 링크 => static/style2.css로 변환됨 -->
    <link rel="stylesheet" href="{% static 'style2.css' %}">
</head>
<body>
    <h2>static 사용하기</h2>

    <h3>static 폴더 사용하기-출력됨</h3>
    <!-- static디렉토리는 걸정을 변경할 수 있음으로
        하드코딩보다는 static태그를 사용하는 것이 보다 안전하다. -->
    <img src="{% static 'apple.png' %}" alt="">
    <img src="/static/mango.png" alt="">
    <img src="/static/banana.png" alt="">

    <!-- 정적(static) 파일은 항상 static디렉토리를 사용해야 한다.
        개발자가 임의로 디렉토리를 추가할 수 없다. -->
    <h3>사용자 폴더 사용하기-출력되지 않음</h3>
    <img src="/images/winter.png" alt="">
    <img src="/static/images/winter.png" alt="">

    <h2>템플릿 태그</h2>
    <h3>for 기본</h3>
    <!-- books는 딕셔너리를 원소로 가진 리스트 임으로
        반복시 점(.)을 이용해서 각 key에 접근할 수 있다. -->
    {% for b in books %}
        <li>{{ b.name }} - {{ b.price }}</li>
    {% endfor %}

    <!-- 반복할 변수에 아무런 값이 없는경우 empty태그를 통해 아래와 같이 출력할 수 있다. 
        if문을 별도로 사용하지 않아도 됨으로 편리하다. -->
    <h3>for ... empty</h3>
    {% for h in hobbys %}
        <li>{{ h.name }}</li>
    {% empty %}
        <li>내용없음</li>
    {% endfor %}

    <!-- 
        counter : 실제 반복에서의 카운트를 반환.(1부터)
        counter0 : 실제 반복에서의 카운트를 반환.(0부터)
        revcounter : 루프 끝에서 몇번째인지 카운트(1부터)
        revcounter0 : 루프 끝에서 몇번째인지 카운트(0부터)
        first : 반복의 처음일때 true반환
        last : 반복의 마지막일때 true반환
        parentloop : 상위 루프를 의미함으로 단일 for문일때는 결과 없음.
     -->
    <h3>for에서 사용되는 변수</h3>
    {% for b in books %}
        <li>
            {{ forloop.counter }} -
            {{ forloop.counter0 }} -
            {{ forloop.revcounter }} -
            {{ forloop.revcounter0 }} -
            {{ forloop.first }} -
            {{ forloop.last }} -
            {{ forloop.parentloop }} {# 아무것도 안나옴 #}
        </li>
    {% endfor %}

    <h3>중첩된 for문</h3>
    {% for f in favorites %} <!-- 4회 반복 -->
        {% for b in books %} <!-- 3회 반복 -->
        <li>
            <!-- 부모의 favorites가 포함된 for문의 속성이 출력된다 -->
            {{ forloop.parentloop }}
        </li>
        {% endfor %}
    {% endfor %}    

    <h3>일반적인 for문 사용하기</h3>
    <!-- range(1,11) 로 선언한 변수임으로 1~10까지 반복 -->
    {% for i in iVar %}
        {{ i }} <br>
    {% endfor %}

    <!-- 파이썬과 동일하게 2개 이상의 조건에서는 elif를 사용한다. -->
    <h2>if문</h2>
    {% if hobbys %}
        hobbys 갯수 : {{ hobbys|length }} <!-- hobbys의 길이 출력-->
    {% elif books %}
        books의 갯수 : {{ books|length}}
    {% else %}
        모두 False임
    {% endif %}
    <br>
    {% if num > 50 and num < 200 %}
        num 은 50보다 크가
    {% else %}
        num은 50보다 작다
    {% endif %}

    <!-- 특정값을 변수에 저장한다. 단, with 블럭내에서만 사용할 수 있다. -->
    <h2>with</h2>
    {% with total=books|length %}
        with블럭안 : {{ total }} <br>
    {% endwith %}
    <!-- 블럭을 벗어나면 소멸되어 출력되지 않는다. -->
    with블럭밖 : {{ total }}

    <!-- URLConf에 지정된 네임스페이스를 통해 확장성 있는 URL을 생성재둔다.
        특히 URL에 변수처리를 해야할 경우 유용하게 사용할 수 있다. -->
    <h2>url</h2>
    <li>url1 : {% url 'tempapps:my_filter' %}</li>
    <li>url2 : {% url 'tempapps:my_tag' %}</li>
    <li>url3 : {% url 'livepolls:detail' 10 %}</li>
    <li>url4 : {% url 'livepolls:results' 20 %}</li>
    <!-- 
        url4는 아래와 매칭되어 URL을 생성한다.
        path('<int:question_id>/results/', views.results, name='results')
        ※ livepolls폴더 안의 urls.py파일의 => app_name의 값 + path의 name
    -->
</body>
</html>

ProjectRoot/tempapps/templates/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>가입완료</title>
</head>
<body>
    <h2>감사합니다.</h2>
    <p>
        입력한 아이디는 {{ user_id }} 입니다.
    </p>
</body>
</html>